tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-highest": "#293833",
                "primary-fixed-dim": "#95d3ba",
                "inverse-surface": "#d6e6df",
                "tertiary-fixed": "#e4e4cc",
                "surface-container-low": "#101e1a",
                "surface-container-high": "#1f2d28",
                "on-error": "#690005",
                "error-container": "#93000a",
                "on-primary": "#003829",
                "tertiary-fixed-dim": "#c8c8b0",
                "on-tertiary-container": "#b3b49d",
                "on-secondary-fixed": "#241a00",
                "on-primary-fixed": "#002117",
                "surface-container": "#14221e",
                "on-tertiary-fixed-variant": "#474836",
                "on-secondary-container": "#342800",
                "tertiary-container": "#444634",
                "surface": "#081612",
                "outline": "#89938d",
                "error": "#ffb4ab",
                "inverse-primary": "#2b6954",
                "primary-fixed": "#b0f0d6",
                "surface-tint": "#95d3ba",
                "tertiary": "#c8c8b0",
                "background": "#081612",
                "on-secondary-fixed-variant": "#574500",
                "on-tertiary": "#303221",
                "on-surface-variant": "#bfc9c3",
                "surface-bright": "#2e3c37",
                "surface-variant": "#293833",
                "primary": "#95d3ba",
                "surface-container-lowest": "#04110d",
                "secondary-container": "#af8d11",
                "on-surface": "#d6e6df",
                "on-primary-fixed-variant": "#0b513d",
                "secondary-fixed-dim": "#e9c349",
                "on-error-container": "#ffdad6",
                "secondary-fixed": "#ffe088",
                "surface-dim": "#081612",
                "on-tertiary-fixed": "#1b1d0e",
                "on-primary-container": "#80bea6",
                "primary-container": "#064e3b",
                "on-secondary": "#3c2f00",
                "secondary": "#e9c349",
                "inverse-on-surface": "#25332f",
                "on-background": "#d6e6df",
                "outline-variant": "#404944"
            },
            fontFamily: {
                "headline": ["Noto Serif"],
                "body": ["Plus Jakarta Sans"],
                "label": ["Plus Jakarta Sans"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
}
